version: '3.8'

services:
  backup-to-minio:
    image: backup-to-minio:latest
    container_name: backup-to-minio
    volumes:
      - ./config.yml:/config.yml:ro
      # - ./data:/data:ro
      # - ./tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      # - /var/lib/docker:/var/lib/docker
    env_file:
      - .env
    command: ["/usr/local/bin/backup-tool"]
