version: '3.8'

services:
  backup-to-minio:
    image: backup-to-minio:latest
    container_name: backup-to-minio
    volumes:
      - ./config.yml:/config.yml:ro
      - test:/data:ro
      # - ./tmp:/tmp
      # - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: ["/backup-tool"]

volumes:
  test:
    external: true